X=MsgBox("reboot?",4+32,"lol") 
X=MsgBox("hahaha",4+32,"lol") 
X=MsgBox("reboot?",4+32,"lol") 
X=MsgBox("hahaha",4+32,"lol") 
X=MsgBox("reboot?",4+32,"lol") 
X=MsgBox("hahaha",4+32,"lol") 
X=MsgBox("reboot?",4+32,"lol") 
X=MsgBox("hahaha",4+32,"lol") 
